MethodLength:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - script/**/*
    - db/**/*
    - config/**/*
    - tmp/**/*
    - log/**/*
    - spec/spec_helper.rb
